language: php

sudo: false

php:
    - 7.1
    - 7.2
    
matrix:
    fast_finish: true

services:
    - mongodb

env:
    - SYMFONY_VERSION=3.4.* DB=pdo_mysql DB_USER=root DB_NAME=lexik_test
    - SYMFONY_VERSION=4.0.* DB=pdo_mysql DB_USER=root DB_NAME=lexik_test
    - SYMFONY_VERSION=4.1.* DB=pdo_mysql DB_USER=root DB_NAME=lexik_test

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [ -x .travis/before_install.sh ]; then .travis/before_install.sh; fi;

install:
    - if [ -x .travis/install.sh ]; then .travis/install.sh; fi;

script:
    - php vendor/bin/phpunit -v
